package edu.wpi.teamo;

public enum Pages {
    MEDICINE,
    PATHFINDING,
    MAIN,
    SANITATION,
    SERVICEREQUEST,
    MANAGEREQUESTS,
    MAPEDITOR,
    LOADINGSCREEN,
    LOGIN,
    LANGUAGEINTERPRETER,
    RELIGIOUS,
    SURVEY,
    LAUNDRY,
    SECURITY,
    MAINTENANCE,
    ADDUSERS,
    TRANSPORTATION
}
